name: Tag a Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  crear-release:
    runs-on: ubuntu-latest
    steps:
      - name: Cargar aclamaciones
        uses: actions/checkout@v4
      - name: Crear release con Brainiac
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true